In [2]:
import torch
torch.__version__

'1.5.1+cpu'

In [3]:
# Solution to Exercise 2 Tensor Multiplication
snoma = torch.rand(7,7)
snoma

tensor([[2.6634e-01, 9.2855e-01, 4.6345e-01, 2.9884e-01, 5.2571e-01, 2.6441e-01,
         3.9388e-01],
        [3.7871e-01, 3.2018e-01, 5.3071e-01, 9.7007e-01, 9.0999e-01, 8.6238e-01,
         4.5805e-01],
        [7.5985e-01, 1.9706e-01, 9.1937e-02, 9.7171e-01, 1.4941e-01, 4.8363e-01,
         6.0195e-01],
        [8.0242e-01, 9.8916e-01, 7.3628e-02, 7.9943e-01, 4.4363e-01, 4.3333e-04,
         4.7086e-01],
        [4.4456e-01, 8.7261e-01, 5.9162e-01, 7.9776e-02, 8.2284e-01, 5.1562e-02,
         2.5846e-01],
        [1.3903e-01, 8.3463e-01, 2.9652e-01, 8.4281e-01, 4.4884e-01, 1.4970e-01,
         6.9508e-01],
        [3.0127e-01, 7.8122e-01, 6.3237e-01, 6.7894e-01, 4.0703e-01, 2.6502e-01,
         9.9769e-01]])

In [11]:
import torch
tensor = torch.tensor([7, 7])
tensor.shape

torch.Size([2])

In [13]:
# Solution to Exercise 3 Tensor Multiplication
import torch 
tensor = torch.tensor([7, 7])
tensor = torch.tensor([7, 1])
tensor * tensor

tensor([49,  1])

In [15]:
import torch 
torch.manual_seed(0)
snoma1 = torch.rand([7, 7])
snoma2 = torch.rand([7, 1])
snoma1 * snoma2

tensor([[0.2392, 0.3703, 0.0426, 0.0636, 0.1482, 0.3056, 0.2362],
        [0.7349, 0.3735, 0.5184, 0.2860, 0.3293, 0.0183, 0.1384],
        [0.2930, 0.5170, 0.6956, 0.7977, 0.1606, 0.2814, 0.6796],
        [0.6392, 0.2774, 0.6105, 0.2929, 0.3862, 0.6654, 0.0253],
        [0.1051, 0.2119, 0.1732, 0.5290, 0.0998, 0.1531, 0.0855],
        [0.0265, 0.1738, 0.7766, 0.6040, 0.6200, 0.4396, 0.2035],
        [0.1202, 0.0068, 0.0285, 0.0498, 0.1677, 0.1631, 0.0572]])